name: "Canal Isabel II Playwright"
version: "1.0.8"
slug: "canal_isabel_playwright"
description: "Descarga automática de telelecturas del Canal de Isabel II mediante Chromium/Playwright"
url: "https://github.com/osorojo92/canal-isabel-ii-home-assistant"
startup: services
boot: auto
init: false
stage: stable

arch:
  - amd64
  - aarch64

ingress: true
ingress_port: 8099
ingress_entry: "/vnc.html"
panel_icon: "mdi:water"
panel_title: "Canal Isabel II"
panel_admin: true

map:
  - type: share
    read_only: false
  - type: addon_config
    read_only: false

options:
  mode: "auto"
  interval_hours: 24
  startup_delay: 30

schema:
  mode: "list(auto|login)"
  interval_hours: "int(1,168)"
  startup_delay: "int(0,600)"
