worker_processes 1;
pid /tmp/nginx.pid;

error_log /dev/stderr info;


events {

    worker_connections 1024;

}


http {

    include /etc/nginx/mime.types;

    default_type application/octet-stream;


    log_format ingress_debug
        '$remote_addr "$request" '
        'status=$status '
        'ingress="$http_x_ingress_path"';

    access_log /dev/stdout ingress_debug;


    map $http_upgrade $connection_upgrade {

        default upgrade;
        ''      close;

    }


    server {

        listen 8099;

        server_name _;

        root /opt/novnc;


        # ====================================================
        # Página VNC para Home Assistant
        # ====================================================

        location = /vnc.html {

            default_type text/html;

            add_header Cache-Control
                "no-store, no-cache, must-revalidate";

            /*
             * Home Assistant envía X-Ingress-Path.
             *
             * NGINX lo incrusta directamente en el HTML.
             */

            sub_filter_once off;

            sub_filter_types text/html;

            sub_filter
                '__INGRESS_PATH__'
                '$http_x_ingress_path';

            try_files /vnc-ha.html =404;

        }


        # ====================================================
        # WebSocket
        # ====================================================

        location /websockify {

            proxy_pass http://127.0.0.1:6080;

            proxy_http_version 1.1;

            proxy_set_header Upgrade
                $http_upgrade;

            proxy_set_header Connection
                $connection_upgrade;

            proxy_set_header Host
                $host;

            proxy_read_timeout 86400;

            proxy_send_timeout 86400;

            proxy_buffering off;

        }


        # ====================================================
        # Recursos noVNC
        # ====================================================

        location / {

            try_files $uri $uri/ =404;

        }

    }

}